# Generated by Django 3.2.4 on 2021-07-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='default', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
