# Generated by Django 3.2.4 on 2021-07-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210704_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@default.com', max_length=254),
            preserve_default=False,
        ),
    ]
